name: CD

on:
  push:
    branches:
      - master

env:
  DISCORD_HOOK_URL: ${{ secrets.DISCORD_HOOK_URL }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/prefect-flows
  PREFECT__BACKEND: ${{ secrets.PREFECT__BACKEND }}
  PREFECT__SERVER__HOST: ${{ secrets.PREFECT__SERVER__HOST }}
  PREFECT__SERVER__PORT: ${{ secrets.PREFECT__SERVER__PORT }}
  PREFECT__SERVER__PROJECT: ${{ secrets.PREFECT__SERVER__PROJECT }}

jobs:
  build-container:
    name: Build, publish and register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install Python dependencies for deploying
        run: |-
          pip install -r requirements-deploy.txt

      - name: Update image tag in constants
        run: |-
          python .github/workflows/scripts/replace_docker_tag.py $IMAGE_NAME $GITHUB_SHA

      - name: Install package locally
        run: |-
          pip install .

      - name: Configure Docker with gcloud
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build Docker image
        run: |-
          docker build \
            --tag "$IMAGE_NAME:$GITHUB_SHA" \
            .

      - name: Publish Docker image
        run: |-
          docker push "$IMAGE_NAME:$GITHUB_SHA"

      - name: Connect to Tailscale VPN
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Register Prefect flows
        run: |-
          prefect register --project $PREFECT__SERVER__PROJECT -p pipelines/
